### ISSUE TITLE
consider alternative strategy for `uncode()` and `drop.unused.levels`

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#112]
The use of `drop.unused.levels` is confusing, consider something more specific to the uncoding of domains.

**Comment by smroecker** [comment]
They say the hardest part of programming is naming things. Do you have suggestion? My only thought is simplifying it to droplevels, which is the same as the function it's using. I don't know how you get more specific than that. Myself I prefer to appropriate existing names, rather than come up with cute new names.

**Comment by dylanbeaudette** [comment]
Works for me.
