### ISSUE TITLE
optimal chunk sizes for SDA queries

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#126]
Oddly enough `fetchSDA_spatial` seems to perform better with smaller chunk sizes. I suspect that `fetchSDA` (tabular queries / results) would have the opposite performance profile. Either way, it is worth thinking about default chunk sizes. Kudos to Andrew for implementing `fetchSDA_spatial`.

```r
library(soilDB)

# 20 mukey
x <- c("49348", "49359", "49374", "49349", "49350", "49351", "1906226", 
       "49361", "49362", "49363", "49364", "49365", "49366", "49367", 
       "49368", "49369", "51776", "51777", "51778", "51779")

# 13 seconds
system.time(res <- fetchSDA_spatial(x, method="point", chunk.size = 1))
# 20 seconds
system.time(res <- fetchSDA_spatial(x, method="point", chunk.size = 2))
# 47 seconds
system.time(res <- fetchSDA_spatial(x, method="point", chunk.size = 5))
# 91 seconds
system.time(res <- fetchSDA_spatial(x, method="point", chunk.size = 10))
# 177 seconds
system.time(res <- fetchSDA_spatial(x, method="point", chunk.size = 20))
```

**Comment by dylanbeaudette** [comment]
I suspect that a large portion of that time is spent downloading the results (uncompressed JSON).

TODO: talk with Phil about optimal index utilization.

**Comment by kevinwolz** [comment]
I was just independently looking into this because I was surprised that using 20 times the number of chunks actually takes 20 times as long (on my machine at least).  

**I have discovered that there is actually a bug causing this.** 

If you look at the resulting output of the two extremes, you can see that they are not identical. In fact, the output when using 20 chunks is 
```
res20 <- fetchSDA_spatial(x, method="point", chunk.size = 20)
res1 <- fetchSDA_spatial(x, method="point", chunk.size = 1)
nrow(res20@data) / nrow(res1@data)
```

**Comment by kevinwolz** [comment]
I was just independently looking into this because I was surprised that using 20 times the number of chunks actually takes 20 times as long (on my machine at least).

**I have discovered that there is actually a bug causing this.**

If you look at the resulting output of the two extremes, you can see that they are not identical. In fact, the output when using chunk.size = 20 is exactly 20 times as large!

```
res20 <- fetchSDA_spatial(x, method="point", chunk.size = 20)
res1 <- fetchSDA_spatial(x, method="point", chunk.size = 1)
nrow(res20@data) / nrow(res1@data)
[1] 20
```

Indeed, there are exactly 20 times the number of features for _each_ included mukey:
```
table(res1$mukey)
  49348   49349   49350   49351   49359   49361   49362   49363   49364   49365   49366 
    127     230      13      41     224      65     171     284     533     294     111 
  49367   49368   49369   49374   51776   51777   51778   51779 1906226 
     67      93     225     680      21      67      67      29       5 

table(res20$mukey)
 49348   49349   49350   49351   49359   49361   49362   49363   49364   49365   49366 
   2540    4600     260     820    4480    1300    3420    5680   10660    5880    2220 
  49367   49368   49369   49374   51776   51777   51778   51779 1906226 
   1340    1860    4500   13600     420    1340    1340     580     100 

```

The bug lies in the indexing of the `for` loop that starts on line 76 of fetchSDA_spatial.R. To fix this, I would suggest editing lines 76 and 77 to:

```
  for(i in unique(mukey.chunk)) {
    idx <- which(mukey.chunk == i)
```
I've tested this fix and can confirm that the outputs are identical now regardless of chunk size. Happy to do a pull request for this if you like. 


With this fixed, I looked back at the original question posed in this issue. I setup a test that ran 10 reps of each chunk size from 1 to 20. Importantly, each rep shuffles the vector of mukeys so that there no bias introduced by heterogeneity of acreage across mukeys. A better test could be done to actually understand the impact of acreage, but this is at least a start. In the end, there is a complex relationship between chunk size and run time.

```
chunk_test <- function(chunk.size) {
  out <- dplyr::tibble(chunk.size = chunk.size, 
                n.chunks = length(unique(soilDB::makeChunks(x, chunk.size))),
                rep = 1:10, 
                duration = NA)
  
  for(i in 1:nrow(out)) {
    out$duration[i] <- as.numeric(system.time(fetchSDA_spatial_kjw(x = sample(x), method="point", chunk.size = chunk.size))[3])
  }
  
  return(out)
}

test.results <- purrr::map_dfr(1:20, chunk_test)

ggplot(test.results, aes(x = factor(chunk.size), y = duration)) + 
  labs(x = "Chunk size", y = "fetchSDA_spatial runtime (s)") +
  geom_boxplot() +
  geom_text(y = 15, aes(label = n.chunks), vjust = 1)
```

![image](https://user-images.githubusercontent.com/11711566/87573788-0d120b80-c693-11ea-9472-cef2bca1fd59.png)

For now, at least up to 20, it seems like larger chunk sizes are better. Any idea what the limit to this might be? I imagine it would depend on the total acreage associated with the request?

**Comment by dylanbeaudette** [comment]
> I was just independently looking into this because I was surprised that using 20 times the number of chunks actually takes 20 times as long (on my machine at least).

Adding @brownag as he is the function author.

Thanks for testing @kevinwolz. I'm a little embarrassed to see such a rookie mistake in `soilDB`, likely introduced by me when I added chunking / various return geometry types. I can confirm the bug and will commit the fix (per your suggestion)

> **I have discovered that there is actually a bug causing this.**
> 
> If you look at the resulting output of the two extremes, you can see that they are not identical. In fact, the output when using chunk.size = 20 is exactly 20 times as large!
> 
> ```
> res20 <- fetchSDA_spatial(x, method="point", chunk.size = 20)
> res1 <- fetchSDA_spatial(x, method="point", chunk.size = 1)
> nrow(res20@data) / nrow(res1@data)
> [1] 20
> ```
> 
> Indeed, there are exactly 20 times the number of features for _each_ included mukey:
> 
> ```
> table(res1$mukey)
>   49348   49349   49350   49351   49359   49361   49362   49363   49364   49365   49366 
>     127     230      13      41     224      65     171     284     533     294     111 
>   49367   49368   49369   49374   51776   51777   51778   51779 1906226 
>      67      93     225     680      21      67      67      29       5 
> 
> table(res20$mukey)
>  49348   49349   49350   49351   49359   49361   49362   49363   49364   49365   49366 
>    2540    4600     260     820    4480    1300    3420    5680   10660    5880    2220 
>   49367   49368   49369   49374   51776   51777   51778   51779 1906226 
>    1340    1860    4500   13600     420    1340    1340     580     100 
> ```
> 
> The bug lies in the indexing of the `for` loop that starts on line 76 of fetchSDA_spatial.R. To fix this, I would suggest editing lines 76 and 77 to:
> 
> ```
>   for(i in unique(mukey.chunk)) {
>     idx <- which(mukey.chunk == i)
> ```
> 
> I've tested this fix and can confirm that the outputs are identical now regardless of chunk size. Happy to do a pull request for this if you like.

Nice catch and thanks for the suggested fix. No need for a PR, this is a two-liner commit.

> With this fixed, I looked back at the original question posed in this issue. I setup a test that ran 10 reps of each chunk size from 1 to 20. Importantly, each rep shuffles the vector of mukeys so that there no bias introduced by heterogeneity of acreage across mukeys. A better test could be done to actually understand the impact of acreage, but this is at least a start. In the end, there is a complex relationship between chunk size and run time.
>
> For now, at least up to 20, it seems like larger chunk sizes are better. Any idea what the limit to this might be? I imagine it would depend on the total acreage associated with the request?

Thanks for the more nuanced testing, much more realistic than the original post. You are correct: this is a complex operation that cannot be easily understood via simple client-side timings. Some confounding issues:
 * server load
 * SDA query limits (number of concurrent queries)
 * effectiveness of spatial index over different query plans
 * network latency
 * ???

The "sweet-spot" should minimize connection/query overhead (larger `chunk.size`) vs. hitting SDA resource limits (smaller `chunk.size`). This will depend on the number of records affected (there is a 100,000 record limit per query) and the type / complexity of the geometry (there is a ~32Mb JSON serialization limit).  Querying regions with incredibly complex mapping will require smaller `chunk.size`. Some clues / ideas [here](https://github.com/ncss-tech/scale_viz#representative-map-units).

This is a good reminder to make SDA limits more widely known and offer some suggestions.

Thank you very much for bringing this to my attention, submitting a fix, and offering some detailed benchmarks.
Dylan

**Comment by kevinwolz** [comment]
No problem! Glad I could help. 

Just the phrase "fractal dimension" makes my head hurt. That sounds like something that I want no part of! I much prefer the relative simplicity, speed, and small file size of gssurgo, but I'm glad to integrate this into my workflow nonetheless. 

What's the best way for me to get an updated package version that includes the new commit? Is it as simple as `devtools::install_github("ncss-tech/soilDB")`? I tried this and got this error: ERROR: lazy loading failed for package ‘soilDB’.

**Comment by brownag** [comment]
@dylanbeaudette 

@kevinwolz 
Restart your R session before installing  from github -- the package is currently loaded in your session. This is a byproduct of the lazy loading feature used in aqp and soilDB, I think

I take full responsibility for the bad indexing in original commit. I saw this bug last night coincidentally -- when I was testing something completely unrelated in aqp. I unfortunately do not use the above method very much!

If it wasnt for the messages you added Dylan, I wouldnt have even noticed there was anything wrong -- and would have chalked the difference in time up to my high latency internet connection

**Comment by dylanbeaudette** [comment]
> No problem! Glad I could help.
> 
> Just the phrase "fractal dimension" makes my head hurt. That sounds like something that I want no part of! I much prefer the relative simplicity, speed, and small file size of gssurgo, but I'm glad to integrate this into my workflow nonetheless.
> 
> What's the best way for me to get an updated package version that includes the new commit? Is it as simple as `devtools::install_github("ncss-tech/soilDB")`? I tried this and got this error: ERROR: lazy loading failed for package ‘soilDB’.

As @brownag says, restart the R session and then do this:

```r
remotes::install_github("ncss-tech/soilDB", dependencies=FALSE, upgrade=FALSE, build=FALSE)
```

**Comment by dylanbeaudette** [comment]
Before closing this issue, I'll one ore TODO item: add some of this discussion to the relevant manual pages.

- [ ] `SDA_query`
- [ ] `fetchSDA_spatial`
- [ ] ???

**Comment by kevinwolz** [comment]
> As @brownag says, restart the R session and then do this:
> 
> ```r
> remotes::install_github("ncss-tech/soilDB", dependencies=FALSE, upgrade=FALSE, build=FALSE)
> ```

Hmm, I restarted R, but the error persists. Here's the full console output. Looks like it has something to do with the package `Rcpp`.

```
* installing *source* package ‘soilDB’ ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘soilDB’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/soilDB’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/soilDB’
Error: Failed to install 'soilDB' from GitHub:
  (converted from warning) installation of package ‘/var/folders/4p/mpc8rykn1svfp0dd6639lkw40000gn/T//Rtmp8KUQuP/file6f3d3da95f12/soilDB_2.5.6.tar.gz’ had non-zero exit status
```

**Comment by brownag** [comment]
There are some known issues with Rcpp on R 4.0.0 @kevinwolz 

This link might be relevant https://www.gitmemory.com/issue/RcppCore/Rcpp/1100/652675461

**Comment by kevinwolz** [comment]
Updated to R 4.0.2 and that fixed it! Thanks.

**Comment by brownag** [comment]
@kevinwolz Great, thanks again for catching this nasty bug. 

I will address the doc portions of this issue and then close it. 

I think I am inclined to leave the default `chunk.size` at 10, but want to do a little simulation similar to what you did above,

 I am curious about the "incidence of failure" using a chunk size of 20-30  -- rather than some of the details that are discussed RE: total time. If, say, 95% of queries could get through with a chunk size of 30 that would be good justification for upping the limit -- even if some of those were way longer than the average 30 MUKEY query -- that is 3x less queries. However, if on average queries hitting 30 musyms fail 50% of the time, that would not be a good default value (given the constraints of SDA. 

To me, ensuring that a query does not fail, at the cost of some extra iteration, is typically worth it and was the whole reason I designed this routine in the first place. Ha, not quite like I wrote it though! That is def. too much iteration.

**Comment by brownag** [comment]
@dylanbeaudette @kevinwolz So, I have found that when using contiguous sets of MUKEYs (as are often found in the SSURGO database -- mostly a relic of numerical assignment based on political boundaries, only deviating where updates or recent mapping have occurred) the issues with large/complex polygon geometry coming in over the serialization limit is more prevalent. The effects are cumulative, in that adjacent IDs often have similar landscape/mapping style attributes.

Using `sample()` to re-shuffle inputs before chunking appears to eliminate or dramatically reduce the "risk" of erroring out with larger chunk sizes.

It may be that using contiguous IDs is optimal on the server side in terms of spatial query planning -- but that carries a risk of encountering a "bad patch" where either the polygons are huge, or have a lot of vertices, or topologic problems, or whatever.

**Comment by brownag** [comment]
In this example, using random mukeys, I see a (marginal) benefit of increasing chunk size all the way up to `chunk.size >= 80`

```
library(soilDB)
q <- "select top(100000) mukey from mapunit;"
the.keys <- SDA_query(q)

test_fun <- function(n, mukeys) {
  foo <- try(fetchSDA_spatial(mukeys, chunk.size = n))
  good <- !inherits(foo, 'try-error')
  return(list(result = foo, status = good))
}

# how many mukeys total to try?
n.tot <- 120

# calculate a common random index to use
idx <- the.keys[sample(1:nrow(the.keys), n.tot, replace = FALSE),]

# incrementally larger chunk sizes for same "task"
res1 <- test_fun(1, idx) # Done in 4.83 mins; mean/chunk: 2.4 secs; mean/mukey: 2.41 secs.
res2 <- test_fun(2, idx) # Done in 3.61 mins; mean/chunk: 3.6 secs; mean/mukey: 1.81 secs.
res3 <- test_fun(5, idx) # Done in 2.52 mins; mean/chunk: 6.3 secs; mean/mukey: 1.26 secs.
res4 <- test_fun(10, idx) # Done in 2.15 mins; mean/chunk: 10.7 secs; mean/mukey: 1.07 secs.
res5 <- test_fun(20, idx) # Done in 1.88 mins; mean/chunk: 18.8 secs; mean/mukey: 0.94 secs.
res6 <- test_fun(30, idx) # Done in 1.65 mins; mean/chunk: 24.8 secs; mean/mukey: 0.83 secs.
res7 <- test_fun(60, idx) # Done in 1.52 mins; mean/chunk: 45.7 secs; mean/mukey: 0.76 secs.
res9 <- test_fun(80, idx) # Done in 1.4 mins; mean/chunk: 42.1 secs; mean/mukey: 0.7 secs.
res10 <- test_fun(90, idx) # Error
res10 <- test_fun(100, idx) # Error
res8 <- test_fun(120, idx) # Error
```

Which is fascinating, considering that if you try to chunk through that vector of 100k mukeys in order... you will find cases that break with a `chunk.size = 10`!!

```
#### Setting a baseline with a big set of MUKEYs gathered "naively" and chunked in order
#
# ## try chunk size = 100; JSON limit exceeded on 4/1000th chunk [300:400]
fetchSDA_spatial(res$mukey, chunk.size = 100)
# 
# ## try chunk size = 50; some chunks were _very_ slow -- making the server really think 
# ##                      JSON limit exceeded on 18/2000th chunk [900:950]
fetchSDA_spatial(res$mukey, chunk.size = 50)
# 
# ## try chunk size = 25; JSON limit exceeded on 36/4000th chunk  [900:925]
# ##                      the fact that his happened on ~same mukeys as n=50 suggests that 
# ##                      there is some complicated/big polygon geometry for some of those keys
fetchSDA_spatial(res$mukey, chunk.size = 25)
# 
# ## try 25 again, reverse key order to see if we get farther (or not as far)
# ##              we do not get nearly as far. JSON error on 16/4000 [375:400]
fetchSDA_spatial(rev(res$mukey), chunk.size = 25)
# 
# ## use default value of 10 -- JSON limit exceeded on chunk 38/10000 [380:390] -- same spot again!
fetchSDA_spatial(rev(res$mukey))
```

This highlights how there is no general solution -- it is highly dependent on the data being queried -- and the relationships within those data insofar as they interact to produce a result greater or less than 32MB. However, with auto-randomizing mukey inputs, and re-sorting to user input order at the end, we could probably support a much higher default `chunk.size`.

**Comment by brownag** [comment]
This result using 1200 random mukeys, that succeeded with `chunk.size = 30` is heartening.
```
> res2_2 <- test_fun(30, idx) 
Using 40 chunks...
Chunk #1 completed (n_mukey = 30; 25 secs)
Chunk #2 completed (n_mukey = 30; 23.3 secs)
Chunk #3 completed (n_mukey = 30; 32.7 secs)
Chunk #4 completed (n_mukey = 30; 30.9 secs)
Chunk #5 completed (n_mukey = 30; 25.8 secs)
Chunk #6 completed (n_mukey = 30; 52.3 secs)
Chunk #7 completed (n_mukey = 30; 26.1 secs)
Chunk #8 completed (n_mukey = 30; 29.5 secs)
Chunk #9 completed (n_mukey = 30; 23.3 secs)
Chunk #10 completed (n_mukey = 30; 21.8 secs)
Chunk #11 completed (n_mukey = 30; 21.3 secs)
Chunk #12 completed (n_mukey = 30; 24.3 secs)
Chunk #13 completed (n_mukey = 30; 28.7 secs)
Chunk #14 completed (n_mukey = 30; 26.3 secs)
Chunk #15 completed (n_mukey = 30; 27.4 secs)
Chunk #16 completed (n_mukey = 30; 33.3 secs)
Chunk #17 completed (n_mukey = 30; 22.6 secs)
Chunk #18 completed (n_mukey = 30; 51.9 secs)
Chunk #19 completed (n_mukey = 30; 32.9 secs)
Chunk #20 completed (n_mukey = 30; 33.6 secs)
Chunk #21 completed (n_mukey = 30; 34.2 secs)
Chunk #22 completed (n_mukey = 30; 1 secs)
Chunk #23 completed (n_mukey = 30; 23.6 secs)
Chunk #24 completed (n_mukey = 30; 39 secs)
Chunk #25 completed (n_mukey = 30; 36.9 secs)
Chunk #26 completed (n_mukey = 30; 27.5 secs)
Chunk #27 completed (n_mukey = 30; 24.9 secs)
Chunk #28 completed (n_mukey = 30; 31.5 secs)
Chunk #29 completed (n_mukey = 30; 32.7 secs)
Chunk #30 completed (n_mukey = 30; 38.2 secs)
Chunk #31 completed (n_mukey = 30; 31 secs)
Chunk #32 completed (n_mukey = 30; 23.9 secs)
Chunk #33 completed (n_mukey = 30; 38.4 secs)
Chunk #34 completed (n_mukey = 30; 33 secs)
Chunk #35 completed (n_mukey = 30; 26.9 secs)
Chunk #36 completed (n_mukey = 30; 36.7 secs)
Chunk #37 completed (n_mukey = 30; 35.1 secs)
Chunk #38 completed (n_mukey = 30; 27.3 secs)
Chunk #39 completed (n_mukey = 30; 31.5 secs)
Chunk #40 completed (n_mukey = 30; 21.1 secs)
Done in 20.8 mins; mean/chunk: 31.2 secs; mean/mukey: 1.04 secs.
```

**Comment by kevinwolz** [comment]
@brownag, wow this is fascinating!

I guess `fetchSDA_spatial()` could "learn" a bit about the supplied mukeys before querying for them to minimize the chances of an error and maximize efficiency. For example, SDA could first be queried to get `muacres` to determine the total number of acres across the mukeys and then allocate mukeys across chunks accordingly. That said, this probably is just not worth it due to the complexity of the problem and likely inability to completely guarantee no error. 

However, the potential for (somewhat unpredictable) errors is quite frustrating. I am using `fetchSDA_spatial()` within a complex of scripts that will be looping through many regions. I would hate to set this up to run overnight, for example, only to find out that it crapped out an hour in. 

I don't have much experience with different ways to "catch" errors within R code, but I know it's possible. Perhaps `fetchSDA_spatial()` could "catch" a failed attempt and iteratively try again with a smaller chunk size until it succeeded?

**Comment by brownag** [comment]
@kevinwolz 

Yes, this is what I am thinking. You are correct there is more to it than total acres. Vertex density is the major problem.

I will try to do that. Do you think it should halve the chunk size (rounded to integer value)?

**Comment by kevinwolz** [comment]
I would suggest a few things: 

1) If your testing makes it clear that chunk sizes greater than X have a greater than 50% failure rate, then I would build this cap into `fetchSDA_spatial()` (i.e. in the documentation and then a check in the code to throw an error when that value is exceeded). Having that error up front will likely save a a ton of headache compared to hitting an error halfway through a script when a problematic set of mukeys is encountered out of the blue.

2) I guess halving the chunk size makes sense. Since, based on your tests, it's not likely to "cost" too much time to halve the chunk size, I don't think there's really a downside in going too small with the second attempt.

3) When the first attempt fails, the function to print that to the screen, along with the new chunk size it's trying.


On another note, I would encourage you to include an option that allows the user to prevent all the printed messages. This is often included via a logical argument called "verbose" or "quietly" or similar.

**Comment by brownag** [comment]
Thanks for the suggestions. Yes, I often include such an argument. I appreciate your input here! 

I would need to set up a more comprehensive testing platform to figure out the true failure rate (i.e. when taking many instances of these random mukey-based tests) -- so that one may be out of reach. 

After thinking about it some more, and your comments, I think that if a "bad chunk" is encountered, each mukey in that chunk should be queried individually. This should all but ensure success.

I do know there used to be some "unqueryable" mukeys -- i.e. you could not query their whole extent at once based on mukey. This was due to a combination of problems. Those things are pretty rare -- and I think fixed now -- regardless I can handle the case of a unit length query failing with a warning that that mukey was dropped from the result due to error (rather than lack of spatial data)

**Comment by kevinwolz** [comment]
That makes a lot of sense to me. Great idea.

**Comment by brownag** [comment]
Retrying that example code that failed  up top with 120 random keys... with new code implemented in a1bd9ff3...

Here is the output (with `verbose = TRUE`) and `chunk.size = 90`

```
> res10 <- test_fun(90, idx) 
# previously error; now done in 3.52 mins; mean/chunk: 101.3 secs; mean/mukey: 1.76 secs.
Using 2 chunks...
Bad chunk encountered. Querying each MUKEY individually...
Chunk #1_sub completed (n_mukey = 1; 2.4 secs)
Chunk #1_sub completed (n_mukey = 1; 1.9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.6 secs)
Chunk #1_sub completed (n_mukey = 1; 1.9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 2.6 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 2.1 secs)
Chunk #1_sub completed (n_mukey = 1; 2.3 secs)
Chunk #1_sub completed (n_mukey = 1; 4.2 secs)
Chunk #1_sub completed (n_mukey = 1; 1.6 secs)
Chunk #1_sub completed (n_mukey = 1; 0.9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.8 secs)
Chunk #1_sub completed (n_mukey = 1; 1 secs)
Chunk #1_sub completed (n_mukey = 1; 2.1 secs)
Chunk #1_sub completed (n_mukey = 1; 1.5 secs)
Chunk #1_sub completed (n_mukey = 1; 2.2 secs)
Chunk #1_sub completed (n_mukey = 1; 0.9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 3.7 secs)
Chunk #1_sub completed (n_mukey = 1; 4.8 secs)
Chunk #1_sub completed (n_mukey = 1; 1.2 secs)
Chunk #1_sub completed (n_mukey = 1; 4 secs)
Chunk #1_sub completed (n_mukey = 1; 1.3 secs)
Chunk #1_sub completed (n_mukey = 1; 1.6 secs)
Chunk #1_sub completed (n_mukey = 1; 1.3 secs)
Chunk #1_sub completed (n_mukey = 1; 1.6 secs)
Chunk #1_sub completed (n_mukey = 1; 1.2 secs)
Chunk #1_sub completed (n_mukey = 1; 2.3 secs)
Chunk #1_sub completed (n_mukey = 1; 1.3 secs)
Chunk #1_sub completed (n_mukey = 1; 1.5 secs)
Chunk #1_sub completed (n_mukey = 1; 1.7 secs)
Chunk #1_sub completed (n_mukey = 1; 1.9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.9 secs)
Chunk #1_sub completed (n_mukey = 1; 0.9 secs)
Chunk #1_sub completed (n_mukey = 1; 5.3 secs)
Chunk #1_sub completed (n_mukey = 1; 5 secs)
Chunk #1_sub completed (n_mukey = 1; 1.3 secs)
Chunk #1_sub completed (n_mukey = 1; 1.8 secs)
Chunk #1_sub completed (n_mukey = 1; 2.4 secs)
Chunk #1_sub completed (n_mukey = 1; 2.2 secs)
Chunk #1_sub completed (n_mukey = 1; 2.6 secs)
Chunk #1_sub completed (n_mukey = 1; 2 secs)
Chunk #1_sub completed (n_mukey = 1; 6.2 secs)
Chunk #1_sub completed (n_mukey = 1; 1.4 secs)
Chunk #1_sub completed (n_mukey = 1; 1.5 secs)
Chunk #1_sub completed (n_mukey = 1; 2 secs)
Chunk #1_sub completed (n_mukey = 1; 8.2 secs)
Chunk #1_sub completed (n_mukey = 1; 3.4 secs)
Chunk #1_sub completed (n_mukey = 1; 1 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 0.9 secs)
Chunk #1_sub completed (n_mukey = 1; 3.3 secs)
Chunk #1_sub completed (n_mukey = 1; 2.5 secs)
Chunk #1_sub completed (n_mukey = 1; 1.5 secs)
Chunk #1_sub completed (n_mukey = 1; 2.1 secs)
Chunk #1_sub completed (n_mukey = 1; 1.8 secs)
Chunk #1_sub completed (n_mukey = 1; 1.5 secs)
Chunk #1_sub completed (n_mukey = 1; 1 secs)
Chunk #1_sub completed (n_mukey = 1; 2.4 secs)
Chunk #1_sub completed (n_mukey = 1; 5.4 secs)
Chunk #1_sub completed (n_mukey = 1; 0.9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 1 secs)
Chunk #1_sub completed (n_mukey = 1; 1 secs)
Chunk #1_sub completed (n_mukey = 1; 1 secs)
Chunk #1_sub completed (n_mukey = 1; 1.4 secs)
Chunk #1_sub completed (n_mukey = 1; 2.2 secs)
Chunk #1_sub completed (n_mukey = 1; 2.9 secs)
Chunk #1_sub completed (n_mukey = 1; 9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.4 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 2.3 secs)
Chunk #1_sub completed (n_mukey = 1; 1.6 secs)
Chunk #1_sub completed (n_mukey = 1; 1 secs)
Chunk #1_sub completed (n_mukey = 1; 2 secs)
Chunk #1_sub completed (n_mukey = 1; 1.4 secs)
Chunk #1_sub completed (n_mukey = 1; 2.5 secs)
Chunk #1_sub completed (n_mukey = 1; 1.2 secs)
Chunk #1_sub completed (n_mukey = 1; 1 secs)
Chunk #1_sub completed (n_mukey = 1; 1.9 secs)
Chunk #1_sub completed (n_mukey = 1; 1.1 secs)
Chunk #1_sub completed (n_mukey = 1; 1.7 secs)
Chunk #1_sub completed (n_mukey = 1; 2.4 secs)
Chunk #1_sub completed (n_mukey = 1; 1.2 secs)
Chunk #1_sub completed (n_mukey = 1; 1.5 secs)
Chunk #1_sub completed (n_mukey = 1; 0.8 secs)
Chunk #2 completed (n_mukey = 30; 15.8 secs)
Done in 3.52 mins; mean/chunk: 101.3 secs; mean/mukey: 1.76 secs.
```

There is a "significant" performance penalty (on average, a second per mukey) for the above ... buuuut it finishes! Many mukeys done individually that could have been chunked... but notice there are a couple "easter eggs" in there that took 8-9 seconds each! I abstracted the guts of the function out, and tweaked a couple things in `SDA_query` to allow the errors to be handled.

I think `90` might be a bit of a high value to use as a rule -- especially given this behavior -- since the per-mukey rate does not seem to get all that much faster increasing `chunk.size` beyond 20-30ish -- but perhaps in some areas it would be feasible. Nonetheless, demonstrates the new functionality well.

**Comment by dylanbeaudette** [comment]
Thanks for the excellent discussion and further stress-testing of these functions. I'm in favor of making them more robust to SDA resource limit "errors" that can't easily be anticipated. There will be a limit to which the current approaches can expect to guarantee results when asking for full geometry. I haven't tested the (known) monster polygons since our latest refresh, but I expect that there are still map units with either single instances or cumulative vertex counts that will exceed the JSON serialization limit.

A two-pass solution seems like a good idea: start with a reasonable chunk size, keep track of errors on the first-pass and try again with singleton chunks. A word of caution in the documentation should be added: there is no reason to expect that SDA will deliver everything you ask it for when using the REST/JSON interface. It was never designed to offer a complete, on-demand alternative to local files. That said, there should be no cursed delineations that are effectively un-queryable.

For tinkering, mukey `161428` is a fine example of complex geometry.

I'll ask our lead SDA developer about a convenience function for estimating the size of results in terms of resource limitations: e.g. expected affected rows and estimated JSON size.

**Comment by brownag** [comment]
Awesome -- I tested the complex mukey you provided.

```
> library(soilDB)
> res <- fetchSDA_spatial("161428")
Using 1 chunks...
Chunk #1 completed (n_mukey = 1; 36.9 secs)
Done in 36.9 secs; mean/chunk: 36.9 secs; mean/mukey: 36.87 secs.
```

It was another stress test on my timing code -- much longer than a typical mukey. Above it finished in ~35s for a single mukey, but when I tried it the other it took over a minute. which messed up my assumption that a single mukey would never take longer than a minute for displaying seconds. Ha.

I added some basic discussion to `SDA_query` and updated the `fetchSDA_spatial` docs. I also made some changes to the docs and examples in the `mapunit_geom_by_ll_bbox` docs -- so that covers the ??? part of the documentation todo list you made. @dylanbeaudette feel free to change the wording on anything I wrote and/or reopen this issue. I can add to my todo list that a vignette or tutorial is warranted for this function -- or SDA_query and this function as part of it.

**Comment by brownag** [comment]
![image](https://user-images.githubusercontent.com/20842828/88008195-975bd480-cac4-11ea-990a-3bdf8b33ed08.png)

The image of the beast

**Comment by dylanbeaudette** [comment]
> Awesome -- I tested the complex mukey you provided.
> 
> ```
> > library(soilDB)
> > res <- fetchSDA_spatial("161428")
> Using 1 chunks...
> Chunk #1 completed (n_mukey = 1; 36.9 secs)
> Done in 36.9 secs; mean/chunk: 36.9 secs; mean/mukey: 36.87 secs.
> ```
> 
> It was another stress test on my timing code -- much longer than a typical mukey. Above it finished in ~35s for a single mukey, but when I tried it the other it took over a minute. which messed up my assumption that a single mukey would never take longer than a minute for displaying seconds. Ha.

That is one of the worst offenders, but maybe not the worst. I'll dig up a couple more for testing.

> I added some basic discussion to `SDA_query` and updated the `fetchSDA_spatial` docs. I also made some changes to the docs and examples in the `mapunit_geom_by_ll_bbox` docs -- so that covers the ??? part of the documentation todo list you made. @dylanbeaudette feel free to change the wording on anything I wrote and/or reopen this issue. I can add to my todo list that a vignette or tutorial is warranted for this function -- or SDA_query and this function as part of it.

Thanks. I'll take a look at the docs tomorrow. I'm not sure but large WFS requests via `mapunit_geom_by_ll_bbox` may actually be more efficient for some queries--I'll ask out lead SDA dev about it. Good reminder to circle back to the old SDA tutorials and maybe write another one. The short talk for the upcoming Western Regional NCSS meetings is a good reason to make some progress.
