### ISSUE TITLE
SDA-based aggregation and composite e.g. (E/B) horizons

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#282]
Are there really horizons in SSURGO that share the same depths? If so, how would one properly compute weighted mean values over some depth interval or SOC stocks?

I haven't found any. Probably missing something.
```sql
CREATE TEMP TABLE xx AS
SELECT cokey, hzname, hzdept_r, hzdepb_r, count(hzname) 
FROM ssurgo.chorizon group by cokey, hzname, hzdept_r, hzdepb_r 
HAVING count(hzname) > 1;
```

**Comment by brownag** [comment]
SSURGO has only aggregate data for composite horizons, right? I think your query result backs that up. I don't know that there is a way to reverse engineer it from SSURGO alone as the proportions aren't in `chorizon`

Weighted mean values over some depth interval would just use the aggregate L, RV, H values.
Possibly also using the L/H range for top/bottom depths when they are populated?

I am reminded of https://github.com/ncss-tech/soilDB/issues/122 for a good description of the pedon data side of the problem and some sample datasets. The Total Vol Pct and/or Total Lateral Area Pct could presumably be used for aggregation of composite horizons from component pedon(s) when these have been linked to components?

**Comment by dylanbeaudette** [comment]
Yeah, I thought that was the case. A cooperator quoted some bit of SSURGO metadata that I hadn't seen before:

"Horizons that have
two distinct parts, such as E/B or
E&Bt horizons, are recorded twice.
Once for the characteristics of the
first part; and again on another
row, using the same depths and
thicknesses, for the characteristics
of the other part."

... which appears in the metadata / help for the chorizon table:

https://sdmdataaccess.nrcs.usda.gov/documents/TablesAndColumnsReport.pdf

I'm wondering if this possibility was superseded by guidance or regional practices that effectively split the composite horizon across unique depths. I have seen many cases of multiple, adjacent E/B horizons--however, with different depths.

Thanks for bringing up #122, this is a long-standing issue that has and will continue to hamper our collection / use of pedon data in AK.

**Comment by brownag** [comment]
> ... which appears in the metadata / help for the chorizon table

Yeah, that same statement is used in NASIS tables documentation for chorizon and the phorizon. Not clear if it is just an unintended duplication of statement from Pedon -> Component or indeed if the overlap was intended for component data.

> I'm wondering if this possibility was superseded by guidance or regional practices that effectively split the composite horizon across unique depths. 

It seems to me that 50/50 weighting of the components is too limited. Even if WSS and other standard aggregation methods support it (it is not clear they do), overlap as described in metadata probably doesn't "do what we want"

You can get closer to a proportional weighting with, as you describe with multiple adjacent E/B, subdividing including a small amounts of E or B as needed. 

While for 1cm slices it is not as accurate weighting, over the practical aggregation interval of most interpretations and derived properties it is close. There is no need for "overlap with matching depths" without an attribute that can be used to support weighted aggregation of component parts.

As far as how to deal with overlap in aggregations in general--algorithms should calculate rather than assume the cumulative thickness of parts, such that there is no inflation of values when taking thickness-weighted values over a fixed depth interval. This assumes that 50/50 for overlap in lieu of a sub-horizon level weight.

**Comment by brownag** [comment]
Any further thoughts on this? Was there somewhere in soilDB where these types of stock calculations were going to be implemented?

**Comment by dylanbeaudette** [comment]
I can't find any such overlapping horizons in SSURGO, so best to close the issue. I'm working on assembling an AK example dataset in aqp (pedons) for further experimentation there. I'll open a new soilDB ticket if/when we need it.
