### ISSUE TITLE
Randomly bad calls to fetch data

### ISSUE THREAD

**Issue by kevinwolz** [ncss-tech/soilDB#310]
I have been making lots and lots of calls to `mukey.wcs`, `get_mapunit_from_SDA`, and similar SDA-querying functions lately. Most of the time, things seem to work fine, but then suddenly, even when using the same exact query, I get "bad WCS request" or "empty result set". For some AOIs or mukeys, the problem seems persistent. For others it is random and transient. I **think** this is separate from some of the edge cases that I have brought up elsewhere. 

Here's an example of one county that is persistently returning "bad WCS request" when calling `mukey.wcs`.

```
library(sf)
library(soilDB)
library(dplyr)
aoi <- st_read("CT007.kml")
aoi.mukey.grid <- mukey.wcs(aoi = aoi, db = "gssurgo", res = 30, quiet = TRUE)
```

But I guess it's not totally persistent, because it worked yesterday at least long enough for me to know what mukeys are in it. Here's one of those mukeys and a call using that to `get_mapunit_from_SDA`, which consistently returns "empty result set".

```
mukeys <- 285931

where <- mukeys %>% 
  as.integer() %>% 
  paste0("'", ., "'") %>% 
  toString() %>% 
  paste0("mukey IN (", ., ")")

get_mapunit_from_SDA(WHERE = where)
```

Is this some instability related to the Oct 1 data refresh?

**Comment by brownag** [comment]
> Is this some instability related to the Oct 1 data refresh?

I think so.

The `mukey.wcs()` failures are because the SoilWeb server that hosts the WCS is/was down. I believe it is in the process of being refreshed to catch up with the new live SSURGO data. I think all `mukey.wcs()` requests are currently failing.

For the `get_mapunit_from_SDA()` request... that mukey appears to not exist in the current SSURGO. If it _previously_ returned data then that mukey has been replaced in the latest refresh. As mapunits and soil survey legends are updated from year to year mukeys can change. 

```
SDA_query("SELECT * FROM mapunit WHERE mukey=285931")
#> empty result set
#> NULL
```

**Comment by brownag** [comment]
Ah, correction, @dylanbeaudette updated the URL for the web service here: https://github.com/ncss-tech/soilDB/commit/fd42e574c55fc96b9d42b03fc80a0f19e523b24d

Now we are going to be using the load balancer #309 so hopefully that should make WCS requests more stable.

Soil Data Access also has intermittent downtime, often in the middle of the night in the US, so that could explain errors with SDA_query-based approaches.

**Comment by kevinwolz** [comment]
Hmm, maybe I should take a break from this project for a few weeks while the refresh propagates everywhere and stabilizes!

**Comment by dylanbeaudette** [comment]
Confirming that the SoilWeb WCS and related resources are now correctly handled by the load-balancer. You will need the latest version of {soilDB}.

Note that we are now in the strange in-between time where gSSURGO/gNATSGO are out of sync with SSURGO proper (SDA).

**Comment by kevinwolz** [comment]
Great! I imagine it usually takes a few weeks for this "in-between" time to end?

**Comment by dylanbeaudette** [comment]
I'll ask, but it could be a couple of months before gSSURGO and gNATSGO are rebuilt.

**Comment by brownag** [comment]
If last year is any indication (looking at last years upload times on the Box site of January 2023), I would not expect the gSSURGO/gNATSGO to be available until the start of calendar year 2024. Closing this as the SoilWeb server is back up and load balanced. Note that SDA has the new refreshed FY23 data, whereas mukey.wcs() is still on FY22.
