### ISSUE TITLE
Most reliable way to get sample year for NCSS?

### ISSUE THREAD

**Issue by potash** [ncss-tech/soilDB#365]
What is the best way to get the year that an NCSS pedon was sampled? There is the `samp_classdate` but my understanding is that this occasionally gets revised when a sample is reclassified? The `upedonid` also usually contains a year and sometimes it seems to predate the `samp_classdate`, e.g. `"S2002VA163050"` seems to be 2002 but has a `samp_classdate` in 2006.

If `samp_classdate` is not reliably the sampling year, is there another column that is? Or is manually parsing the year from `upedonid` my best bet? Thanks!

**Comment by brownag** [comment]
I would suggest using `lab_combine_nasis_ncss.site_obsdate` rather than any of the "classification" dates. 

This is the NASIS site observation date. In some cases this may not be the "actual site observation date" but just the "entry creation date". Unfortunately there is no way to distinguish the "site observation date kind" from the `lab_combine_nasis_ncss` table alone, but it could be identified from the "companion pedon" (morphologic) database, `siteobs.obsdatekind` column, downloadable from here: https://ncsslabdatamart.sc.egov.usda.gov/database_download.aspx

In general `samp_classdate` is the "sampled as" classification. It should not get revised once it is entered. but that is not to say that never happens. Sometimes it may get updated to newer version of taxonomy, missing components added after lab data comes back, etc. I think it is common that the "sampled as" classification doesn't get populated until some time after the site was observed. `corr_classdate` is the "correlated" classification, which is where updated classifications should go. The `corr_classdate` is usually newer than the sampled as date, if present. `SSL_classdate` is classificationby the lab--and may be more consistently populated for data from historic/non-KSSL sources.

**Comment by potash** [comment]
Thanks @dylanbeaudette @brownag  this is super helpful.
