### ISSUE TITLE
conversion of NASIS data to factors should use ordered factors when appropriate

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#53]
The use of `uncode()` gets close, but the ordering of rows in the metadata tables aren't always based on meaningful rankings. Fragment hardness is a good example of levels that should be ordered from least "hard" to most "hard".

The use of ordered factors would make it possible to use `<` and `>` for filtering.

**Comment by brownag** [comment]
**Regarding ordered factors:** This could be a really neat feature that allows us to incorporate knowledge about / reason over relationships between our different categorical vars.

**Regarding fetchNASIS automatically converting to factor (and using domain value list verbatim):**
However, we may want to think about the strategy for converting NASIS data to factors. How do we handle domains that contain (very) infrequently observed obsolete values? For instance, the slope curvature domains include "complex" and "undulating" -- these aren't used in the modern site/soil description and NASIS interface does not allow you to use them... but there must be legacy data that uses them.

The domains provide an opportunity to impose some order... but automatically `factor()`-ing and including obsolete factor levels by default is a bit strange to me. Granted, in the initial soil survey context we rarely have to deal with the obsolete things... so it is easy to say that we should have a "toggle" to include obsolete (otherwise return a warning similar to the other warnings that crop up when validating the SPC). I recognize that my view on this is just that. SDJR and other more far-reaching uses of NASIS may need these things more readily accessible.

@jskovlin brought up that it is important that we don't obscure or omit certain obsolete values... for instance old taxonomy. 

I agree with that. And I think it makes sense for the fetch functions to do uncoding e.g. numeric -> human-readable values. But we may want to leave it at that. Leave handling of NASIS-specific factoring be a suite of functions available in the soilReports package, and individual reports.

Looking forward to discussing this further.

**Comment by dylanbeaudette** [comment]
Agreed. The automatic conversion to factors has created some bugs (smashed and yet to be discovered) in those functions and reports that depend on the output from `fetchNASIS()`.

I would rather that `fetchNASIS()` or any function that compiles NASIS data set just those factor levels that are relevant to the purpose of the function (e.g. the behavior prior to switching to `uncode()`).

A simple solution: `uncode()` gets an argument `factors=FALSE` that toggles setting factor levels. This argument could be passed down from `fetchNASIS()`.

**Comment by smroecker** [comment]
Generally the factor ordering imposed by uncode() has seemed pretty good to me, and has been more helpful than not. Pre-uncode() I was having to manually set the order of character data A LOT for tables and figures. I have no issue with adding an additional argument to uncode() or fetchNASIS. Although I think it should be stringsAsFactors = TRUE to be consistent with the rest of R (and save me the trouble of having to order my data ;) ).

**Comment by dylanbeaudette** [comment]
One more idea, add an argument to `uncode()` such that obsolete entries are excluded.

**Comment by dylanbeaudette** [comment]
Here are a couple of routes, based on 1:1 conversations with the usual suspects:

   * `uncode()` gets an argument which toggles automatic conversion to factors
      + setting the default for `fetchNASIS()` is still a point of contention
   * `fetchNASIS()` does none or very limited factor conversion by default, another function performs factor conversion on the SPC
   * `uncode()` is slightly refactored into *uncoding* and *factor-level-setting* pieces

Pre-soilDB 1.8.16 `fetchNASIS()` did limited factor conversion so that things like surface shape came out in an "intuitive" order in tables / figures--see `get_site_data_from_NASIS_db()` for examples. For now, I think that an argument to `uncode()` is the simplest, pending time that someone might have to implement a more nuanced approach.

We can vote on it, but I'll leave the final decision to Stephen as he is the lead on soilDB.

**Comment by dylanbeaudette** [comment]
Stephen: what do you think about having `uncode()` default to `factors=FALSE` when invoked via `fetchNASIS()`?

**Comment by smroecker** [comment]
I think soilDB should behave consistently regardless of the function. So if the consensus is that soilDB should return strings by default, then so be it.  

My vote is that we should add the argument stringsAsFactors = default.stringsAsFactors() to soilDBs suite of functions in order to be consistent with base R and allow users to set their preference with options(stringsAsFactors). I've tested this with uncode(), get_component_data_from_NASIS_db() and options(), and it seems to work well.

I realize that the previous behavior of soilDB was to return strings. So there is a compelling argument that this ship has sailed, and therefore that stringsAsFactors = FALSE should be the default for soilDB. 

I know it's now 'fashionable' to set options(stringsAsFactors = FALSE) or employ the tidyverse dialect (I've used both myself). However, I haven't seen a great discussion about the pros and cons of this issue, other than storage (http://bit.ly/stringsfactorsbio).  As best I can tell from what little bit testing I've done, factors act as characters for the most commonly used character functions (e.g. paste, grepl, substr, ==, and stringr derivatives), except for nchar and strsplit. However as I noted earlier, one of the major benefits of factors is their order is preserved in plots and tables. For me, benefits of 'maintaining the ordering' outweighs the 'handful of string functions' that would require calling as.character(). 

**Regarding ordered factors**
Where uncode() doesn't return the desired order, we could manually reorder that variable within uncode(). However, I've not sure how this will affect the invert argument.

**Obsolete factors**
Removing obsolete factors or levels seems like a 'bad' idea to me. For example, "SDJR" is now an obsolete projecttypename. So how would soilDB handle this? Exclude all SDJR projects, or return blank entries for projecttypename. Either case results in throwing away data.

**Comment by brownag** [comment]
Personally, I have no need for the _default_ soilDB functionality to be returning strings. For most folks, and quick visualization in graphs/tables/etc., the factors probably make things easier.

I'd be fine if have to toggle for the (relatively rare) cases where I don't want it to factor things. As long as we know what the standard is, we could adjust individual reports to conform. It's not like wrapping a var in as.character(), and re-factoring with desired levels for e.g. a particular table is all that hard. 

My beef with the obsolete factors was merely that some of the old reports (which did not previously include unobserved, obsolete levels) all of a sudden started returning empty entries for the obsoletes. This, again, is a report and domain specific problem. Which is why I argued that perhaps this type of view-oriented factoring should be relegated to an accessory function in soilReports. I see that nobody really jumped on that as an idea, so might not be the right/easiest way to go.

I don't think we should be altogether omitting obsoletes, at least not silently. Jay raised the issue of old taxonomy, Stephen the issue of projecttypes. Perhaps a check to see if there are any OBSERVED obsolete values in the query results, and dropping if n=0 for that level is a good compromise. I don't really like the idea of dropping factor levels with no observations if they are NOT obsolete, since that would make certain logical classes "disappear" from tables where the fact that n=0 for that class might be important. Also, from a data quality perspective, I think we should have some way of flagging when a particular SPC is returned containing obsolete levels. Something like the below when calling `fetchNASIS()`
```-> QC: pedons/horizon attributes with obsolete levels: use `get('obsolete.factor.levels', envir=soilDB.env)for related pedon IDs```

It also seems that there is a difference in terms of whether you can use a particular obsolete value in NASIS. In the example I gave above with curvature, the obsoletes are not even available for use in the NASIS interface/drop-down. For Stephen's example, SDJR is still an option (marked with "(Obsolete)").

**Comment by jskovlin** [comment]
I like the idea of dropping empty factor levels with no observations (whether obsolete or not) because I can't really think of many (well any?) cases where intentionally populating no data would be 'meaningful'.  On the reports side it might in cases be meaningful to array all the domain choice levels (obsolete and not obsolete) and show where the data falls, but other than that I think the retention of empty factor levels is unnecessary overhead.  Most of the time we are concerned with what the data is more than what it is not within the given array of choices.

**Comment by dylanbeaudette** [comment]
I have noticed that needless conversion to factors can lead to some unintended outcomes:

   1. Objects with factors that contain many levels are huge. For example the taxhistory table, split into pieces by `peiid` is > 1.5Gb due to the very large number of levels associated with each taxonomic element. Clearly, these kind of data do not need to be stored as factors. I can think of a number of cases where factors aren't relevant. Perhaps this would help:

```r
# factors aren't helpful here
d.taxhistory <- uncode(d.taxhistory, stringsAsFactors = FALSE)
```

   2. Unused factor levels are very annoying when using `table` or any graphics function that relies on factor  levels. Sure, it is possible to re-level by calling `factor()` one more time.

**Comment by smroecker** [comment]
I agree. Particularly with taxonomic terms where ordering is less of an issue, and the more typical use cases are pattern matching which doesn't always play nice with factors. On a related note. I'm thinking we should add a drop.unused.levels argument to uncode() and set the default to TRUE. While ordered factors are generally useful, the addition of unused factors usually seems to be  a burden.

**Comment by dylanbeaudette** [comment]
Great. I made the above change so that the taxhistor table isn't converted into factors. Makes a significant difference in terms of the total memory footprint of `fetchNASIS_pedons`. I suspect that there may be some similar issues with the component data fetching code.

I like dropping un-used levels. All of the factors that I need the full set of levels are automatically set in `fetchNASIS`, after the data have been loaded. For example:
   * hillslope position
   * drainage class
   * etc.

This might be a good time to make sure that there is code in place for setting the full set of levels and ordering them (when possible) is consistent.

**Comment by smroecker** [comment]
Ok I've added the drop.unused.levels argument to uncode(). For the time being I've left the default as FALSE, so as not to disrupt any existing functions that use uncode(), but if others want to test we can switch to TRUE. I tested setting it to TRUE with the SDA functions, and didn't noticed any issues. So it's probably safe to switch.

**Comment by dylanbeaudette** [comment]
Thanks.

BTW, I think that `droplevels()` can work on an entire `data.frame`.

**Comment by smroecker** [comment]
I know, but it's just seemed safer to do it that way.

**Comment by smroecker** [comment]
Does anyone have any other complaints, besides the related issue from #112? Otherwise for me this issue should be closed. uncode() has been give two arguments to address the primary issues listed above (e.g. stringsAsFactors = TRUE and drop.unsed.levels = TRUE).

For those fields that aren't currently sorting correctly I recommend too options.
1. Do it manually inside your function or report.
2. Submit a NASIS data model request to George to change the sequencing the metadata domains.

**Comment by brownag** [comment]
@smroecker 

I personally am satisfied with the (stringsAsFactors & drop.unsed.levels) for controlling factor levels. 

My preference is to generally for #1 -- and I think we could develop some helper functions that are designed to facilitate this -- for reuse in downstream reports. 

Maybe there are some fields where a data model change is warranted? I don't have any specific ones in mind.

**Comment by dylanbeaudette** [comment]
Thanks @smroecker. I' also prefer option 1: there is no guarantee that the domains are ordered "correctly", and, in most cases it depends on the context. It looks like I've mixed a couple of issues together in this thread.
