### ISSUE TITLE
Linking NASIS component data to SSURGO spatial data.

### ISSUE THREAD

**Issue by phytoclast** [ncss-tech/soilDB#74]
A critical data field that we will need to make R effective in mining NASIS for the purposes of assigning components to PESs is the “lmapunitiid”. If I understand it correctly, a table consisting of “dmuiidref” and “lmapunitiid” should suffice. This field is needed to relate components to mukey of SSURGO spatial data. The may be only way to effectively link the component data to spatial joined tables consisting of mukeys and ecoregions, or gridded climatic data from PRISM (derived in ArcGIS).

**Comment by dylanbeaudette** [comment]
OK. `fetchNASIS(from='components')` doesn't load these data because most DMU-related queries do not load information from "higher-up". If those tables (Legend, LegendMapUnit, etc.) are populated, then you can get the data elements you need via `get_component_correlation_data_from_NASIS_db()` as of 64fda60ca52153d074c144ccd4bdd37ebbad8c93. Be sure to install the latest version of soilDB like this:

```r
devtools::install_github("ncss-tech/soilDB", dependencies=FALSE, upgrade_dependencies=FALSE)
```
