### ISSUE TITLE
normalize parent material, geomorp, ecosite, flattening strategies

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#84]
There are several implementations which all do slightly different things:
   *  `.copm_prep`: applies to data returned by SDA
   * `.formatParentMaterialString`: applies to pedon objects
   * `.formatcoParentMaterialString`: applies to component objects

The strategies used by `formatcoParentMaterialString` and `formatParentMaterialString` are more or less the same, with the component version employing additional checks on the source data. Missing or inconsistent record IDs, sequence numbers, vertical order sequences, and "exists on" logic contribute to the complexity of the code.

There are likely some corner-cases not yet handled by these functions, see #83 for an example.

Notes to myself for next time.
```r
library(soilDB)

x <- fetchNASIS(from='components')
knitr::kable(site(x)[1:5, c('compname', 'pmkind', 'pmorigin')])

z <- fetchNASIS(from='pedons')
knitr::kable(site(z)[10:15, c('taxonname', 'pmkind', 'pmorigin', 'bedrckkind')])
```

**Comment by dylanbeaudette** [comment]
See also #47

**Comment by brownag** [comment]
With recent work on fetchNASIS (https://github.com/ncss-tech/soilDB/commit/0b3d5177382f79c4c6a68538905a50e702ef848c) `.formatcoParentMaterialString` has been deprecated in favor of `.formatParentMaterialString` for component data.

**Comment by brownag** [comment]
I believe this issue has been resolved. 

The `.formatcoXXX()` functions have been subsumed into `.formatXXX() for NASIS.

In this issue we are not going to address harmonizing the above parent material funcitons with the SDA function `.copm_prep()`  that is used for SDA and SSURGO File Geodatabases.

A variety of new tools and derived values are available for geomorph and parent material in the NASIS and SDA derived results compared to when this issue was made in 2018. If there are any specific further needs, let's create a new issue.
