### ISSUE TITLE
finish NASIS component queries and return similar objects as pedon queries

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#9]
## TODO
1. complete re-write of original code [done]
2. finish adding functions / columns for `fetchNASIS()` parity
3. new tutorial explaining usage (#128)
4. fix old code that is now broken

**Comment by brownag** [comment]
I think this issue was adequately completed a while back. There are of course some differences between components and pedons that necessitate different treatement... and there are good issues in the tracker to further generalize "flattening" so in theory the same functions could be applied to similar data. Currently we are carrying parallel versions of some child table management functions for pedon and component.
