### ISSUE TITLE
add diagnostics to fetchSDA_cmponent & ensure similar offerings are available for different SPC data sources

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#93]
I think that wherever possible the high-level SPC constructors (`fetchXXX`) should provide the same basic functionality. 

Diagnostic features:
`fetchSDA_component()` does not return diagnostic features.  `fetchOSD()` doesn't either.
`fetchNASIS_component` & `fetchNASIS_pedon` _do_ return diagnostics.

Related to #34

**Comment by brownag** [comment]
```
get_SDA_diagnostics <- function(my.spc) {
  target_cokeys <- site(my.spc)[,idname(my.spc)]
  q <- paste0('SELECT * FROM codiagfeatures WHERE cokey IN ', format_SQL_in_statement(target_cokeys), ";")
  return(SDA_query(q))
}

diagnostic_hz(my.spc) <- get_SDA_diagnostics(my.spc)
```

**Comment by dylanbeaudette** [comment]
These are good ideas. Feel free to implement, with updates to manual pages and tests.

`fetchOSD` will get diagnostic features when more OSD pedons have been established in NASIS and given a first round of QC. Long-term `fetchOSD` will return elements from NASIS site/pedon objects instead of whatever I can glean from the parsed OSD text.

**Comment by brownag** [comment]
ff3bfda
