### ISSUE TITLE
NAMESPACE re-working

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/soilDB#99]
Related to [aqp/#85](https://github.com/ncss-tech/aqp/issues/85)

This doesn't work, why?
```r
library(soilDB)
data("loafercreek", package = 'soilDB')
slot(loafercreek, 'sp')
```

```
Error in e[1, 2] : subscript out of bounds
```

For now, `R CMD build` may fail while running examples. This has to do with method dispatch for `plot.SoilprofileCollection`.

**Comment by dylanbeaudette** [comment]
Ideas:
   * http://www.hep.by/gnu/r-patched/r-exts/R-exts_33.html
   * http://r-pkgs.had.co.nz/namespace.html#exports

**Comment by brownag** [comment]
`Error in e[1, 2]: subscript out of bounds` is what happens when you have an uninitialized `SpatialPoints` in the `@sp` slot of the SoilProfileCollection. It causes problems if you accidentally access it before setting up the Spatial slot with `coordinates<-`. 

Was the `loafercreek` dataset historically serialized to file while promoted to Spatial-SPC? That could be the source of inconsistency here. Pretty sure I didn't do that the last several times I have built the object.

The SpatialPoints not having a viable EMPTY state is a major reason I favor lighter-weight option for the `@sp` slot -- a list/data.frame containing the coordinates, or just column names from `@site` (like other SPC slots: `idname`, `hzdepthcols`, `hzidname`) pointing at coordinates plus a place for the CRS. We could keep all the same S4 methods for setting things up -- just change to a simpler internal representation that we handle our own way, and provide conversion methods for if needed.

``` r
library(aqp, warn.conflicts = FALSE)
#> This is aqp 1.27
library(soilDB)

data("loafercreek", package = 'soilDB')
slot(loafercreek, 'sp')
#> class       : SpatialPoints 
#> features    : 1
#> Error in e[1, 2]: subscript out of bounds

loafersub <- subset(loafercreek, !is.na(x_std))
coordinates(loafersub) <- ~ x_std + y_std
slot(loafersub, 'sp')
#> class       : SpatialPoints 
#> features    : 106 
#> extent      : -121.4412, -120.2611, 37.68111, 39.51897  (xmin, xmax, ymin, ymax)
#> crs         : NA
```
